#' Create DeepDive configuration file
#'
#' A function to generate a configuration object containing settings needed to
#' launch DeepDive analyses in Python. Uses formatting compatible with the
#' configparser library in Python via the R package ConfigParser (Hoefling, 2017).
#' The first four arguments describe the data inputs and outputs, while
#' the last five turn on or off major elements of the analytical pipeline.
#' The general module is always mandatory.
#'
#' @param name \code{character}. Name of the analysis, used as a prefix for all
#'    file names linked to an analysis. If multiple analyses are run with the
#'    same name, files are overwritten.
#' @param data_file \code{character}. Name of the file containing empirical
#'    input data generated by `prep_dd_input()`.
#' @param bins \code{numeric}. A `vector` of bin boundary ages.
#' @param n_regions \code{integer}. The number of discrete sampling regions,
#'    e.g. continents, basins. Must be more than or equal to 2.
#'
#' @param simulate \code{logical}. A TRUE/FALSE statement that switches on and
#'    off generation of simulated datasets used in model training and testing.
#'    Defaults to TRUE.
#' @param model_training \code{logical}. A TRUE/FALSE statement that switches on
#'    and off the training of new RNN models. Defaults to TRUE.
#' @param empirical_predictions \code{logical}. A TRUE/FALSE statement that
#'    switches on and off empirical analyses. Defaults to TRUE.
#' @param autotune \code{logical}. When TRUE (default), a new configuration file
#'    will be saved with adjusted parameters used for analyses that reflect the
#'    empirical data.
#' @param add_test \code{logical}. A TRUE/FALSE statement, when true (the
#'    default) a test set with the same settings as the training set are
#'    generated.
#' @param present_diversity \code{numerical}. A numeric value describing the
#'    known diversity at the end of the study interval. In the case a clade is
#'    known to be extinct, this should be set to zero. If the present diversity
#'    is unknown, the default NA can be used.
#'
#' @returns Creates configuration object with settings to launch DeepDive. Once
#'   finalised, configuration files can be saved using
#'   `config$write("file_name.ini")`.
#'
#' @import ConfigParser
#' @examples
#' # Import internal dataset
#' data(carnivora)
#' # Generate vector describing time bin boundaries
#' bins <- c(66, 23, 2.6, 0)
#' # Create configuration object
#' config <- create_config(name = "carnivora",
#'                         data_file = "data/carnivora_deepdive_input.csv",
#'                         bins = bins,
#'                         n_regions = length(unique(carnivora$Region)))
#' @export
create_config <- function(name = NULL, data_file = NULL,
                          bins = NULL, n_regions = NULL,
                          simulate = TRUE, model_training = TRUE,
                          empirical_predictions = TRUE,
                          autotune = TRUE, add_test = TRUE,
                          present_diversity = NA){

  # Handling errors
  if (!is.character(name)) {
    stop("`name` must be a character string.")
  }

  if (is.null(data_file)) {
    stop("`data_file` name must be provided.")
  }

  if (!is.character(data_file)) {
    stop("`data_file` must be a character string.")
  }

  if (!endsWith(data_file, ".csv")) {
    stop(paste("Data file name must end `.csv`."))
  }

  if (is.vector(bins) == FALSE) {
    stop("`bins` should be a vector.")
  }

  if (is.numeric(bins) == FALSE) {
    stop("`bins` should contain numeric values (the ages of bin boundaries).")
  }

  if (is.integer(n_regions) == FALSE) {
    stop("`n_regions` must be an integer.")
  }

  if (!is.logical(simulate) ||
      !is.logical(model_training) ||
      !is.logical(empirical_predictions) ||
      !is.logical(autotune) ||
      !is.logical(add_test)) {
    stop("`simulate`, `model_training`, `empirical_predictions`, `autotune` and
         `add_test` must all be TRUE or FALSE.")
      }

  # Create configuration file frame
  config <- ConfigParser$new()

  # Create subsections
  config$data$general <- c()
  config$data$simulations <- c()
  config$data$model_training <- c()
  config$data$empirical_predictions <- c()

  # Create general directory
  general_settings <- parameters[parameters$module == "general",]

  for (a in 1:nrow(general_settings)) {
    config$data$general[[general_settings[a,2]]] <- general_settings[a,3]
  }

  # Create simulations directory
  simulation_settings <- parameters[parameters$module == "simulations",]

  for (b in 1:nrow(simulation_settings)) {
    config$data$simulations[[simulation_settings[b,2]]] <-
      # Parse R vector as Python vector
      gsub('[c(),]', '', simulation_settings[b,3])
  }

  # Create model training directory
  mt_settings <- parameters[parameters$module == "model_training",]

  for (c in 1:nrow(mt_settings)) {
    config$data$model_training[[mt_settings[c,2]]] <-
      # Parse R vector as Python vector
      gsub('[c(),]', '', mt_settings[c,3])
  }

  # Create empirical predictions directory
  ep_settings <- parameters[parameters$module == "empirical_predictions",]

  for (d in 1:nrow(ep_settings)) {
    config$data$empirical_predictions[[ep_settings[d,2]]] <-
      ep_settings[d,3]
  }

  # Update settings based on provided parameters
  config$data$general$wd <- getwd()

  config$data$general$time_bins <-
    sort(paste(bins, collapse = " "), decreasing = TRUE)
  config$data$general$n_regions <- n_regions
  config$data$general$autotune <- autotune
  config$data$general$present_diversity <- present_diversity
  config$data$general$simulate <- simulate
  config$data$general$model_training <- model_training
  config$data$general$empirical_predictions <- empirical_predictions

  config$data$empirical_predictions$empirical_input_file <- data_file

  #Rename files/folders when name is provided
  if (!is.null(name)) {
    config$data$simulations$sim_name <- paste0(name, "_simulations")
    config$data$simulations$sims_folder <- paste0(name, "_simulations")
    config$data$model_training$sims_folder <- paste0(name, "_simulations")
    config$data$model_training$model_folder <- paste0(name, "_models")
    config$data$model_training$f <- paste0(name, "_feature")
    config$data$model_training$l <- paste0(name, "_label")
    config$data$empirical_predictions$model_folder <- paste0(name, "_models")
    config$data$empirical_predictions$output_file <- paste0(name, "_output")
  }

  #Old code
  #if(add_test == TRUE){
  #  sims$test_seed <- 432
  #  sims$n_test_simulations <- 100  # total number of test simulations
  #}

  #sims$root_r <- paste(0.8*(max(bins)-min(bins))+min(bins), max(bins), collapse="")  # range of ages for origin of clade

  return(config)
}
